steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ["build", "-t", "deenadayalan100887415/platinum-chain-413720/assignment_image:$COMMIT_SHA", "."]
- name: 'gcr.io/cloud-builders/docker'
  args: ["push", "deenadayalan100887415/platinum-chain-413720/assignment_image:$COMMIT_SHA"]
options:
  logging: 'LEGACY'
