steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'northamerica-northeast2-docker.pkg.dev/platinum-chain-413720/deenadayalan-100887415/${SHORT_SHA}', '.']
    
  # Step 2: Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'northamerica-northeast2-docker.pkg.dev/platinum-chain-413720/deenadayalan-100887415/${SHORT_SHA}']

options:
  # Set the defaultLogsBucketBehavior to REGIONAL_USER_OWNED_BUCKET
  logging: REGIONAL_USER_OWNED_BUCKET
