steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/platinum-chain-413720/deenadayalan-100887415/assignment_image:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/platinum-chain-413720/deenadayalan-100887415/assignment_image:$COMMIT_SHA'

  # Deploy Docker container to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'assignment-image'
      - '--image=us-central1-docker.pkg.dev/platinum-chain-413720/deenadayalan-100887415/assignment_image:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--port=3000'
      - '--allow-unauthenticated'

  # Update index.html title
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "<title>Assignment 2 – 100887415</title>" > src/static/index.html
        git add src/static/index.html
        git commit -m "Update index.html title"
        git push origin master
