name: Snyk Security Scan

on:
  push:
    branches:
      - main

jobs:
  snyk_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Authenticate with Snyk
        run: npx snyk auth ${{ secrets.SNYK_TOKEN }}

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        with:
          entryPoint: 'snyk'
          args: 'test'
